# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('AND', 'AS', 'ASSIGN', 'BREAK', 'CLASS', 'COLON', 'COMMA', 'CONTINUE', 'DEF', 'DIFF', 'DIVIDE', 'DIVIDEEQUALS', 'ELIF', 'ELSE', 'EOF', 'EQUALS', 'EXPLAMATION', 'FALSE', 'FOR', 'FROM', 'GLOBAL', 'IF', 'IMPORT', 'IN', 'IS', 'LBRACE', 'LCOLC', 'LPAREN', 'MAIOR', 'MAIOREQUALS', 'MENOR', 'MENOREQUALS', 'MINUS', 'MINUSEQUALS', 'NAME', 'NONE', 'NORMALSTRING', 'NOT', 'NUMBER', 'OR', 'PASS', 'PLUS', 'RBRACE', 'RCOLC', 'RETURN', 'RPAREN', 'SEMICOLON', 'SUMEQUALS', 'TIMES', 'TIMESEQUALS', 'TRUE', 'WHILE', 'WHITESPACE'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NUMBER>\\d+)|(?P<t_newline>\\n+)|(?P<t_NAME>[a-zA-Z_][a-zA-Z_0-9]*)|(?P<t_NORMALSTRING>\\"([^\\\\\\n]|(\\\\.))*?\\")|(?P<t_COMMENT>\\#.*)|(?P<t_ccode_comment>(/\\*(.|\\n)*?\\*/)|(//.*))|(?P<t_EOF>$\\(?![\\r\\n]\\))|(?P<t_IDENTIFIER>[a-zA-Z_]\\w+)|(?P<t_WHILE>while)|(?P<t_WHITESPACE>\\s\\s+)|(?P<t_ELSE>else)|(?P<t_FOR>for)|(?P<t_SUMEQUALS>\\+=)|(?P<t_TIMESEQUALS>\\*=)|(?P<t_DIFF>!=)|(?P<t_DIVIDEEQUALS>/=)|(?P<t_EQUALS>==)|(?P<t_IF>if)|(?P<t_LBRACE>\\{)|(?P<t_LCOLC>\\[)|(?P<t_LPAREN>\\()|(?P<t_MAIOREQUALS>>=)|(?P<t_MENOREQUALS><=)|(?P<t_MINUSEQUALS>-=)|(?P<t_PLUS>\\+)|(?P<t_RBRACE>\\})|(?P<t_RCOLC>\\])|(?P<t_RPAREN>\\))|(?P<t_TIMES>\\*)|(?P<t_ASSIGN>=)|(?P<t_COLON>:)|(?P<t_COMMA>,)|(?P<t_DIVIDE>/)|(?P<t_MAIOR>>)|(?P<t_MENOR><)|(?P<t_MINUS>-)', [None, ('t_NUMBER', 'NUMBER'), ('t_newline', 'newline'), ('t_NAME', 'NAME'), ('t_NORMALSTRING', 'NORMALSTRING'), None, None, ('t_COMMENT', 'COMMENT'), ('t_ccode_comment', 'ccode_comment'), None, None, None, (None, 'EOF'), (None, 'IDENTIFIER'), (None, 'WHILE'), (None, 'WHITESPACE'), (None, 'ELSE'), (None, 'FOR'), (None, 'SUMEQUALS'), (None, 'TIMESEQUALS'), (None, 'DIFF'), (None, 'DIVIDEEQUALS'), (None, 'EQUALS'), (None, 'IF'), (None, 'LBRACE'), (None, 'LCOLC'), (None, 'LPAREN'), (None, 'MAIOREQUALS'), (None, 'MENOREQUALS'), (None, 'MINUSEQUALS'), (None, 'PLUS'), (None, 'RBRACE'), (None, 'RCOLC'), (None, 'RPAREN'), (None, 'TIMES'), (None, 'ASSIGN'), (None, 'COLON'), (None, 'COMMA'), (None, 'DIVIDE'), (None, 'MAIOR'), (None, 'MENOR'), (None, 'MINUS')])]}
_lexstateignore = {'INITIAL': ' \\t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {'INITIAL': 't_eof'}
