
# /home/eliane/CompilerPython/parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'FCFAC6D97F9B6722D042156C70DE76BA'
    
_lr_action_items = {'SUMEQUALS':([0,3,4,5,6,7,13,14,],[3,3,3,3,3,3,3,3,]),'MINUSEQUALS':([0,3,4,5,6,7,13,14,],[4,4,4,4,4,4,4,4,]),'TIMESEQUALS':([0,3,4,5,6,7,13,14,],[5,5,5,5,5,5,5,5,]),'DIVIDEEQUALS':([0,3,4,5,6,7,13,14,],[6,6,6,6,6,6,6,6,]),'LPAREN':([0,3,4,5,6,7,13,14,],[7,7,7,7,7,7,7,7,]),'NAME':([0,3,4,5,6,7,13,14,],[8,8,8,8,8,8,8,8,]),'NUMBER':([0,3,4,5,6,7,13,14,15,16,],[9,9,9,9,9,9,9,9,9,9,]),'TRUE':([0,3,4,5,6,7,13,14,15,16,],[10,10,10,10,10,10,10,10,10,10,]),'FALSE':([0,3,4,5,6,7,13,14,15,16,],[11,11,11,11,11,11,11,11,11,11,]),'NORMALSTRING':([0,3,4,5,6,7,13,14,15,16,],[12,12,12,12,12,12,12,12,12,12,]),'$end':([1,2,8,9,10,11,12,17,18,19,20,22,23,24,25,26,],[0,-27,-55,-2,-3,-4,-5,-14,-15,-16,-17,-10,-11,-12,-13,-54,]),'PLUS':([1,2,8,9,10,11,12,17,18,19,20,21,22,23,24,25,26,],[13,-27,-55,-2,-3,-4,-5,13,13,13,13,13,-10,-11,-12,-13,-54,]),'MINUS':([1,2,8,9,10,11,12,17,18,19,20,21,22,23,24,25,26,],[14,-27,-55,-2,-3,-4,-5,14,14,14,14,14,-10,-11,-12,-13,-54,]),'TIMES':([2,9,10,11,12,],[15,-2,-3,-4,-5,]),'DIVIDE':([2,9,10,11,12,],[16,-2,-3,-4,-5,]),'RPAREN':([2,8,9,10,11,12,17,18,19,20,21,22,23,24,25,26,],[-27,-55,-2,-3,-4,-5,-14,-15,-16,-17,26,-10,-11,-12,-13,-54,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,4,5,6,7,13,14,],[1,17,18,19,20,21,22,23,]),'literal':([0,3,4,5,6,7,13,14,15,16,],[2,2,2,2,2,2,2,2,24,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('empty -> PASS','empty',1,'p_pass','grammar.py',35),
  ('literal -> NUMBER','literal',1,'p_literal','grammar.py',41),
  ('literal -> TRUE','literal',1,'p_literal','grammar.py',42),
  ('literal -> FALSE','literal',1,'p_literal','grammar.py',43),
  ('literal -> NORMALSTRING','literal',1,'p_literal','grammar.py',44),
  ('sequence_literal -> literal COMMA sequence_literal','sequence_literal',3,'p_sequence_literal','grammar.py',49),
  ('sequence_literal -> literal','sequence_literal',1,'p_sequence_literal','grammar.py',50),
  ('variavel -> NAME','variavel',1,'p_variavel','grammar.py',53),
  ('variavel -> NAME LCOLC expression RCOLC','variavel',4,'p_variavel','grammar.py',54),
  ('expression -> expression PLUS expression','expression',3,'p_binary_operators','grammar.py',58),
  ('expression -> expression MINUS expression','expression',3,'p_binary_operators','grammar.py',59),
  ('expression -> literal TIMES literal','expression',3,'p_binary_operators','grammar.py',60),
  ('expression -> literal DIVIDE literal','expression',3,'p_binary_operators','grammar.py',61),
  ('expression -> SUMEQUALS expression','expression',2,'p_operators','grammar.py',82),
  ('expression -> MINUSEQUALS expression','expression',2,'p_operators','grammar.py',83),
  ('expression -> TIMESEQUALS expression','expression',2,'p_operators','grammar.py',84),
  ('expression -> DIVIDEEQUALS expression','expression',2,'p_operators','grammar.py',85),
  ('assign -> ASSIGN expression','assign',2,'p_assign','grammar.py',100),
  ('comparison -> literal MAIOR literal','comparison',3,'p_expression_logop','grammar.py',108),
  ('comparison -> literal MENOR literal','comparison',3,'p_expression_logop','grammar.py',109),
  ('comparison -> literal MAIOREQUALS literal','comparison',3,'p_expression_logop','grammar.py',110),
  ('comparison -> literal MENOREQUALS literal','comparison',3,'p_expression_logop','grammar.py',111),
  ('comparison -> literal EQUALS literal','comparison',3,'p_expression_logop','grammar.py',112),
  ('comparison -> literal DIFF literal','comparison',3,'p_expression_logop','grammar.py',113),
  ('comparison -> literal AND literal','comparison',3,'p_expression_logop','grammar.py',114),
  ('comparison -> literal OR literal','comparison',3,'p_expression_logop','grammar.py',115),
  ('expression -> literal','expression',1,'p_define_expression_literal','grammar.py',140),
  ('statement -> for_statement','statement',1,'p_statement','grammar.py',145),
  ('list_statement -> statement list_statement','list_statement',2,'p_list_statement','grammar.py',150),
  ('list_statement -> empty','list_statement',1,'p_list_statement','grammar.py',151),
  ('eof_statement -> expression EOF','eof_statement',2,'p_statement_eof','grammar.py',154),
  ('import -> FROM NAME IMPORT NAME','import',4,'p_import','grammar.py',160),
  ('import -> IMPORT NAME','import',2,'p_import','grammar.py',161),
  ('end -> EOF','end',1,'p_define_end_of_instruction','grammar.py',172),
  ('colon -> expression COLON','colon',2,'p_colon','grammar.py',176),
  ('dict -> RBRACE expression LBRACE','dict',3,'p_brace','grammar.py',179),
  ('none -> assign NONE','none',2,'p_none','grammar.py',184),
  ('not -> NOT expression','not',2,'p_not','grammar.py',189),
  ('not -> NOT literal','not',2,'p_not','grammar.py',190),
  ('block -> list_statement','block',1,'p_block','grammar.py',196),
  ('for_statement -> FOR expression COLON block','for_statement',4,'p_statement_for','grammar.py',200),
  ('if_statement -> IF comparison COLON block','if_statement',4,'p_statement_if','grammar.py',203),
  ('if_statement -> IF comparison COLON block ELSE COLON block','if_statement',7,'p_statement_if','grammar.py',204),
  ('if_statement -> IF comparison COLON block ELIF comparison COLON block ELSE COLON block','if_statement',11,'p_statement_if','grammar.py',205),
  ('if_statement -> IF comparison COLON block ELIF comparison COLON block','if_statement',8,'p_statement_if','grammar.py',206),
  ('empty -> <empty>','empty',0,'p_empty','grammar.py',217),
  ('while_statement -> WHILE expression COLON block','while_statement',4,'p_statement_while','grammar.py',220),
  ('return_statement -> RETURN','return_statement',1,'p_statement_return','grammar.py',225),
  ('return_statement -> RETURN variavel','return_statement',2,'p_statement_return','grammar.py',226),
  ('break_statement -> BREAK','break_statement',1,'p_statement_break','grammar.py',229),
  ('def_statement -> DEF NAME COLON block','def_statement',4,'p_statement_def','grammar.py',232),
  ('class_statement -> CLASS NAME COLON block','class_statement',4,'p_statement_class','grammar.py',235),
  ('continue_statement -> CONTINUE','continue_statement',1,'p_statement_continue','grammar.py',238),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','grammar.py',241),
  ('expression -> NAME','expression',1,'p_expression_name','grammar.py',246),
]
