
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = 'E42E426BDCF056A98D4A365D0EB4DBC7'
    
_lr_action_items = {'PASS':([0,],[2,]),'$end':([1,2,],[0,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> empty","S'",1,None,None,None),
  ('empty -> PASS','empty',1,'p_pass','grammar.py',24),
  ('literal -> NUMBER','literal',1,'p_literal','grammar.py',28),
  ('literal -> TRUE','literal',1,'p_literal','grammar.py',29),
  ('literal -> FALSE','literal',1,'p_literal','grammar.py',30),
  ('literal -> NORMALSTRING','literal',1,'p_literal','grammar.py',31),
  ('sequence_literal -> literal COMMA sequence_literal','sequence_literal',3,'p_sequence_literal','grammar.py',37),
  ('sequence_literal -> literal','sequence_literal',1,'p_sequence_literal','grammar.py',38),
  ('variavel -> NAME','variavel',1,'p_variavel','grammar.py',42),
  ('variavel -> NAME LCOLC expression RCOLC','variavel',4,'p_variavel','grammar.py',43),
  ('expression -> expression PLUS expression','expression',3,'p_binary_operators','grammar.py',48),
  ('expression -> expression MINUS expression','expression',3,'p_binary_operators','grammar.py',49),
  ('literal -> literal TIMES literal','literal',3,'p_binary_operators','grammar.py',50),
  ('literal -> literal DIVIDE literal','literal',3,'p_binary_operators','grammar.py',51),
  ('expression -> SUMEQUALS expression','expression',2,'p_operators','grammar.py',66),
  ('expression -> MINUSEQUALS expression','expression',2,'p_operators','grammar.py',67),
  ('expression -> TIMESEQUALS expression','expression',2,'p_operators','grammar.py',68),
  ('expression -> DIVIDEEQUALS expression','expression',2,'p_operators','grammar.py',69),
  ('expression -> expression MAIOR expression','expression',3,'p_expression_logop','grammar.py',82),
  ('expression -> expression MENOR expression','expression',3,'p_expression_logop','grammar.py',83),
  ('expression -> expression MAIOREQUALS expression','expression',3,'p_expression_logop','grammar.py',84),
  ('expression -> expression MENOREQUALS expression','expression',3,'p_expression_logop','grammar.py',85),
  ('expression -> expression EQUALS expression','expression',3,'p_expression_logop','grammar.py',86),
  ('expression -> expression DIFF expression','expression',3,'p_expression_logop','grammar.py',87),
  ('expression -> expression AND expression','expression',3,'p_expression_logop','grammar.py',88),
  ('expression -> expression OR expression','expression',3,'p_expression_logop','grammar.py',89),
  ('var_Especification -> NAME LCOLC NUMBER RCOLC','var_Especification',4,'p_var_Especification','grammar.py',111),
  ('var_Especification -> NAME ASSIGN expression','var_Especification',3,'p_var_Especification','grammar.py',112),
  ('var_Especification -> NAME','var_Especification',1,'p_var_Especification','grammar.py',113),
  ('var_Especification -> NAME LCOLC NUMBER RCOLC ASSIGN LBRACE RBRACE','var_Especification',7,'p_var_Especification','grammar.py',114),
  ('expression -> literal','expression',1,'p_define_expression_literal','grammar.py',122),
  ('statement -> for_statement','statement',1,'p_statement','grammar.py',128),
  ('list_statement -> statement list_statement','list_statement',2,'p_list_statement','grammar.py',141),
  ('list_statement -> empty','list_statement',1,'p_list_statement','grammar.py',142),
  ('eof_statement -> expression EOF','eof_statement',2,'p_statement_eof','grammar.py',146),
  ('block -> list_statement','block',1,'p_block','grammar.py',153),
  ('for_statement -> FOR expression COLON block','for_statement',4,'p_statement_for','grammar.py',158),
  ('if_statement -> IF expression COLON block','if_statement',4,'p_statement_if','grammar.py',162),
  ('if_statement -> IF expression COLON block ELSE COLON block','if_statement',7,'p_statement_if','grammar.py',163),
  ('if_statement -> IF expression COLON block ELIF COLON block ELSE COLON block','if_statement',10,'p_statement_if','grammar.py',164),
  ('if_statement -> IF expression COLON block ELIF expression COLON block','if_statement',8,'p_statement_if','grammar.py',165),
  ('while_statement -> WHILE expression COLON block','while_statement',4,'p_statement_while','grammar.py',173),
  ('return_statement -> RETURN','return_statement',1,'p_statement_return','grammar.py',177),
  ('return_statement -> RETURN variavel','return_statement',2,'p_statement_return','grammar.py',178),
  ('break_statement -> BREAK','break_statement',1,'p_statement_break','grammar.py',182),
  ('def_statement -> DEF expression COLON block','def_statement',4,'p_statement_def','grammar.py',186),
  ('class_statement -> CLASS expression COLON block','class_statement',4,'p_statement_class','grammar.py',190),
  ('continue_statement -> CONTINUE','continue_statement',1,'p_statement_continue','grammar.py',194),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression','grammar.py',198),
]
